# Configuration for the GitLab CI.

stages:
  - test

# Go tests, on various Go versions.
.golang_template: &golang
  stage: test
  script:
    - go test ./...
    - go test -race ./...

golang_1.15:
  <<: *golang
  image: golang:1.15  # Oldest supported version (for now).

golang_latest:
  <<: *golang
  image: golang:latest


# Integration test, using the module versions from the repository.
integration_stable:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t dnss-test -f tests/Dockerfile .
    - docker run --name test1 dnss-test
  after_script:
    - docker cp test1:/go/src/blitiri.com.ar/go/dnss docker-out/
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - docker-out/


# Integration test, using the latest module versions.
integration_latest:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t dnss-test --build-arg GO_GET_ARGS="-u=patch" -f tests/Dockerfile .
    - docker run --name test1 dnss-test
  after_script:
    - docker cp test1:/go/src/blitiri.com.ar/go/dnss docker-out/
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - docker-out/
