# Configuration for https://travis-ci.org/

language: go
go_import_path: blitiri.com.ar/go/dnss
dist: bionic

jobs:
  include:
    - name: "go 1.11 (debian stable)"
      go: 1.11.x
      # Enable Go modules explicitly on Go 1.11.
      # Some packages update in backwards-incompatible ways assuming Go
      # modules are in use, which can break the build unexpectedly.
      env: GO111MODULE=on
    - name: "go stable"
      go: stable
    - name: "go tip"
      go: master
  allow_failures:
    # There is a bug in the Travis environment where it can't reach certain
    # hosts that host Go package dependencies.
    # This manifests only in Go 1.11, since subsequent versions use the public
    # proxy which has no problems.
    # Make the build optional until the issue is fixed.
    - go: 1.11.x


script:
    - go test ./...
    - go test -bench . ./...
    - go test -race -bench . ./...

